export {default as LandingPage} from  './Landing'
export {default as SignInPage} from  './SignIn'
export {default as SignUpPage} from  './SignUp'
export {default as DashboardPage} from  './Dashboard'
export {default as ContactPage} from  './Contact'
export {default as ResetPasswordPage} from  './ResetPassword'
export {default as ForgotPasswordPage} from  './ForgotPassword'
export {default as NotFoundPage} from  './NotFound'